#!/bin/bash
tmux has-session -t dashboard 2>/dev/null

if [ $? != 0 ]; then
  # create session
  tmux new-session -d -s dashboard -n main

  # split into left and right halves
  tmux split-window -h -t dashboard:main

  # send commands to panes
  tmux send-keys -t dashboard:main.0 'taskwarrior-tui' Enter
  tmux send-keys -t dashboard:main.1 'notepad' Enter

  # attach
  tmux attach -t dashboard
else
  tmux attach -t dashboard
fi
